---

- name: Remove target_operator_group
  kubernetes.core.k8s:
    api_key: "{{ api_key | default(omit) }}"
    api_version: operators.coreos.com/v1
    kind: OperatorGroup
    kubeconfig: "{{ kubeconfig_path }}"
    name: "{{ target_operator_group }}"
    namespace: "{{ target_namespace }}"
    state: absent
    wait: true
  register: _result
