---

- name: Print information for cluster api
  debug:
    msg: 
      - "System is ready with {{ description }} Installed, Cluster can be found at: "
      - "API URL: {{ cluster_api_url }}"
      - ""
      - "export KUBECONFIG={{ kubeconfig_path }}"
  changed_when: true

- name: Print information for cluster console
  debug:
    msg:
      - "Console URL: {{ console_url }}"
      - "Console Username: {{ console_username }}"
      - "Console Password: {{ console_password }}"
  changed_when: true
  when: console_url is defined

- name: Print information for accessing WebSphere Automation UI
  debug:
    msg: 
      - "UI url: {{ hostvars['was-automation']['ui_access_uri'] }}"
      - "UI username: {{ hostvars['was-automation']['ui_access_credentials']['admin_username'] | b64decode }}"
      - "UI password: {{ hostvars['was-automation']['ui_access_credentials']['admin_password'] | b64decode }}"
  changed_when: true
  when: description == 'WebSphere Automation'
