---

- name: Allow pods to run on master nodes
  kubernetes.core.k8s:
    api_key: "{{ api_key | default(omit) }}"
    api_version: config.openshift.io/v1
    definition:
      spec:
        mastersSchedulable: true
    kind: Scheduler
    kubeconfig: "{{ kubeconfig_path }}"
    name: cluster
    state: patched
  register: _result
